<?php
/**
 * @file
 * The main functionality of this module.
 */

module_load_include('inc', 'tripal_ws_brapi_testdata', 'class/TripalWebServiceTestData');


/**
 * Implements hook_menu().
 */
function tripal_ws_brapi_testdata_menu() {
  $items = [];

  $items['tripalwsbrapi/testdata'] = [
    'title'       => 'TRIPAL BrAPI Calls Test Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_ws_brapi_generate_data'),
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  $items['tripalwsbrapi/testsearch'] = [
    'title'       => 'TRIPAL BrAPI Calls Test Search Calls',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tripal_ws_brapi_search'),
    'access arguments' => ['access content'],
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Function callback (page callback), begin processing call request.
 */
if (!function_exists('tripal_ws_brapi_generate_data')) {
  function tripal_ws_brapi_generate_data($form, &$form_state) {
    // In this order, project info is required in phenotype, and organism
    // info is require in stocks.
    // Reverse order when remove command to prevent triggers from table constraints.
    $source = [
      'project'    => ['main' => 'project-csv', 'prop' => 'projectprop-csv'],
      'project_relationship' => ['main' => 'project_relationship-csv'],
      'organism'   => ['main' => 'organism-csv'],
      'stock'      => ['main' => 'stock-csv', 'prop' => 'stockprop-csv'],
      'phenotype'  => ['main' => 'phenotype-csv' , 'prop' => 'phenotypeprop-csv', 'cvtermprop' => 'cvtermprop-csv'],
      'contact'    => ['main' => 'contact-csv', 'prop' => 'contactprop-csv'],
      'genotype'   => ['main' => 'genotype-csv'],
      'feature'    => ['main' => 'feature-csv', 'prop' => 'featureprop-csv', 'feature_relationship' => 'feature_relationship-csv', 'genotype_call' => 'genotype_call-csv'],
      'featuremap' => ['main' => 'featuremap-csv', 'prop' => 'featuremapprop-csv', 'featuremap_organism' => 'featuremap_organism-csv', 'featurepos' => 'featurepos-csv'],
      'cvterm'     => ['main' => 'cvterm-csv'],
    ];

    $testdata = new TripalWebServiceTestData($source);

    // Establish request to load or request remove test data.
    if (isset($form_state['values'])) {
      $btn_value = $form_state['values']['tripal_ws_btn_command'];
      if ($btn_value == 'Remove Test Data' || $btn_value == 'Load Test Data') {
        $request = ($btn_value == 'Remove Test Data') ? 'remove' : 'load';
        $testdata->doRequest($request);
      }
    }

    // Create a summary table in tabs.
    $sort = $_GET['sort'];
    if ($sort == 'asc' || $sort == 'desc' || $sort == 'none') {
      $sort = $sort;
    }

    $request = 'summary';
    $property = $testdata->doRequest($request, ['sort' => $sort]);

    // Convert properties returned into Drupal from objects.
    drupal_set_message($property['message']);

    // Command/request button.
    $form['tripal_ws_btn_command'] = [
      '#type'   => 'button',
      '#value'  => $property['button'],
      '#prefix' => '<div style="top: 30px; right: 0; position: absolute;">',
      '#suffix' => '</div>',
      '#id'     => 'tripal-ws-brapi-request-button'
    ];

    // Summary table.
    $form['#attached']['library'][] = array('system', 'ui.tabs');
    $form['tripal_ws_tabs'] = [
      '#markup' => $property['summary']
    ];

    return $form;
  }
}

/**
 * Function callback (page callback), construct test search form.
 */
if (!function_exists('tripal_ws_brapi_search')) {
  function tripal_ws_brapi_search($form, &$form_state) {

    $form['tripal_ws_textfield_url'] = [
      '#type' => 'textfield',
      '#title' => t('Call URL'),
      '#size' => 60,
      '#default_value' => $GLOBALS['base_url'] . '/web-services/brapi/v1/search/',
      '#required' => TRUE,
    ];

    $form['tripal_ws_textfield_tip'] = [
      '#markup' => '<div>Parameter name + : (colon) + values (comma separated). Example germplasmDbIds:123,456,789</div>'
    ];

    $param = [
      '#type' => 'textfield',
    ];

    foreach(range(0, 4) as $i) {
      $param['#title'] = t('Parameter #' . ($i + 1));
      $form['tripal_ws_textfield_param' . $i] = $param;
    }

    $form['tripal_ws_btn_submit'] = [
      '#type' => 'submit',
      '#value' => 'POST',
    ];

    return $form;
  }
}


/**
 * Implements hook_submit().
 * Create post search request.
 */
if (!function_exists('tripal_ws_brapi_search_submit')) {
  function tripal_ws_brapi_search_submit($form, &$form_state) {
    if ($form_state['values'] && !empty($form_state['values'])) {
      // Search URL.
      $url = $form_state['values']['tripal_ws_textfield_url'];

      // Parameters.
      $param = [];
      foreach(range(0, 4) as $i) {
        $param_name = 'tripal_ws_textfield_param' . $i;

        if ($form_state['values'][ $param_name ] && !empty($form_state['values'][ $param_name ])) {
          @list($name, $val) = explode(':', $form_state['values'][ $param_name ]);

          if ($name == 'pageSize' || $name == 'page') {
            $param[$name] = (int) $val;
          }
          else {
            $param[$name] = explode(',', $val);
          }
        }
      }

      // Construct POST request.
      $ch = curl_init();
      curl_setopt($ch, CURLOPT_URL, $url);
      curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
      curl_setopt($ch, CURLOPT_HEADER, FALSE);
      curl_setopt($ch, CURLOPT_POST, TRUE);
      // Parameter
      curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($param));

      curl_setopt($ch, CURLOPT_HTTPHEADER, ["Content-Type: application/json"]);
      $response = curl_exec($ch);
      curl_close($ch);


      $get_response = $url . '?searchResultDbId=HASH CODE';
      drupal_set_message('Replace the <strong>HASH CODE</strong> in this URL <u>' . $get_response . '</u> with the searchResultDbId value in the respose below: <p> ' . $response . '</p>');
    }
  }
}
