<?php
/**
 * Call: Calls, class definition.
 * Search for a set of germplasm based on some criteria.
 */
class TripalWebServiceBrapiV2SearchGermplasm extends TripalWebServiceSearchCall {
  // Call existing and identical call already setup.
  // Declare existing call.
  //
  // module name / char v + major version number / call name.
  public static $is_alias_of = 'tripal_ws_brapi/v1/search/germplasm';
}
